- client/src/components/LoginPage.jsx
- client/src/components/MainPage.jsx
- client/src/contexts/UserContext.jsx
- client/src/main.jsx
User accessible when existing user, but not accessible when user has just signed up (issue being worked on).
> Adds user context (for existing users)

- package-lock.json
Save changes to package-lock.json
> Save changes to package-lock.json

- client/src/App.jsx
- client/src/components/Chat.jsx
- client/src/components/ConnectionCard.jsx
- client/src/components/ConnectionsPage.jsx
- client/src/components/MessageCard.jsx
- client/src/styles/Connections.css
- client/src/styles/MessageCard.css
- Fixed navigation to Chat component on app.jsx file
- Added MessageCard Component
- Added MessageCard.css file
- Worked on Chat.jsx file
> Chat integration init. Fixed navigation to chat on app.jsx file

- client/src/components/FilterOptions.jsx
- client/src/components/LearningList.jsx
- client/src/components/MainPage.jsx
- client/src/components/MatchCard.jsx
- client/src/components/MatchList.jsx
- client/src/contexts/UserContext.jsx
- Fixes matching bug in MatchList
- Fixes LearningList
> Match list

- client/src/components/LoginPage.jsx
- client/src/components/ProtectedRoutes.jsx
Protected routes working as intended now. Can only access routes if logged in.
> Protected routes working

- client/src/components/UserShowcase.jsx
- client/src/styles/showcase.css
Very basic text area showcase that updates and fetches
> Basic showcase added

- client/src/components/FilterOptions.jsx
- client/src/components/UserDropdown.jsx
- client/src/components/UserInterests.jsx
- client/src/components/UserPage.jsx
- client/src/components/UserPicture.jsx
Reverting due to issues with master branch
> Revert "Fixing userpage display"

- client/src/components/UserDropdown.jsx
Added the ability to type a username which creates a chat with that person
> User Dropdown- Connect 

- client/src/components/Chat.jsx
- client/src/components/ConnectionCard.jsx
- client/src/components/ConnectionsPage.jsx
- client/src/components/MessageCard.jsx
- client/src/styles/MessageCard.css
Updated information shown on connection cards, chat header, and message cards. On connection cards/chat headers now shows chat title or chat with [names] by default. On Message cards shows user name and time of post
> Updated - Chat integration

- client/src/components/UserPage.jsx
- client/src/styles/Reviews.css
Added functionality for reviews on userpage
> Added reviews function to UserPage

- client/src/components/Chat.jsx
- client/src/components/MessageCard.jsx
- client/src/styles/MessageCard.css
Added basic delete functionality to chat messages
> Added basic delete functionality to chat messages

- client/src/components/UserInterests.jsx
- client/src/components/UserIntroSkills.jsx
- client/src/components/UserPicture.jsx
- Adds conditional rendering of edit functionality in UserPicture, UserInterests, and UserIntroSkills
> Conditional rendering userpage

- client/src/components/LearningList.jsx
- client/src/components/MatchCard.jsx
- client/src/components/MatchList.jsx
- client/src/styles/App.css
- Removes duplicates from both match and learning lists
- Adds skills and interests to cards
- Adds some general styling for list and cards
> Updates Lists and Matchcard

- client/src/components/ConnectionCard.jsx
- client/src/components/ConnectionsPage.jsx
- client/src/styles/Connections.css
Added basic delete functionality on chats. Connection card updated with basic styling
> Delete chats added - Basic styling for connection cards

- client/src/contexts/UserContext.jsx
Makes usercontext to be stored in local storage to make it persist even after refresh
> Usercontext update

- client/src/components/LearningList.jsx
Loading state correctly works.
> Loading state

- client/src/components/Chat.jsx
Fix: chat input now resets when sending message
> Fix: chat input now resets when sending message

- client/src/styles/MessageCard.css
Fixes chat scaling and word wrap
> Fixes chat scaling and word wrap

- client/src/components/Chat.jsx
- client/src/components/MessageCard.jsx
- client/src/styles/MessageCard.css
Adds chat navigation by clicking on user names on chat header or message cards in the chat
> Chat integration update - navigation

- client/src/components/UserPage.jsx
- client/src/components/UserUsername.jsx
- client/src/components/UserpageConnect.jsx
Added connect button to userpage  so you can create a chat with someone through their page
> Added Connect button onto UserPage, new component called UserpageConnect

- client/src/components/UserPicture.jsx
Fix user avatar update when updating image by updating the local storage of usercontext. Image will update as soon as the user navigates out of the profile or refreshes
> User avatar fix

- client/src/components/UserDescription.jsx
- client/src/components/UserReviews.jsx
- client/src/components/UserShowcase.jsx
- client/src/components/UserUsername.jsx
- client/src/styles/UserPage.css
- client/src/styles/showcase.css
- Improves styles in username
- Improves styles in showcase
- Improves styles in description
> Userpage fixes

- client/src/components/UserDescription.jsx
- client/src/components/UserShowcase.jsx
- client/src/components/UserUsername.jsx
- client/src/styles/UserPage.css
- client/src/styles/showcase.css
- Adds edit emoji to username, description and showcase buttons
- Makes all font sizes equal
- Adds some padding in showcase
> Adds edit emoji and adds some styling

- client/src/components/UserDropdown.jsx
Fixes duplicates chat creation by adding chat post validation
> Connect fix
